### ISSUE TITLE
terraform cloud scripts for azure

### ISSUE THREAD

**Issue by hardjopranoto** [citrix/terraform-cloud-scripts#10]
hi george, 
do you have a terraform scripts for deploying adc in azure?

**Comment by giorgos-nikolopoulos** [comment]
Hi @hardjopranoto .

No we don't currently have terraform scripts for deploying ADC in azure.

There is this [repository](https://github.com/citrix/netscaler-azure-templates) which contains Azure Resource Manager templates.

Perhaps you could use them as a basis for building the corresponding terraform scripts.

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #18
